### PR TITLE
shovel: deployed contract address data

### PR DESCRIPTION
**Pull request by regynald**
Added contract address from transaction receipt rpc response to `Receipt` struct. This can be null so current filters ops don't work to only filter non null contract address values. I also added a new `nonEmpty` filter op for byte arrays (slices).

Admittedly, the filter op that doesn't use args felt kind of hacky so would love suggestions on if and how I should change that.

### CODE REVIEW

**Comment by ryandotsmith** [comment]
Nice. Thank you for the PR! I wonder if we can reuse the `eq` and `ne` operators. Maybe filter where the address `ne` with an empty arg? I noticed that the accept function returns early when no arg is supplied, but I bet we can change that to return early if `len(f.Op) == 0`. This is kind of a PITA because we should probably update the code that reads `f.Arg[0]` later in the function to use a zero-value for the type if `len(f.Arg) == 0`. WDYT?

**Comment by regynald** [comment]
That makes sense to me. Though if might make sense to do something like a nonEmpty down the line if more nullable data types are added. Will make a patch!

**Comment by ryandotsmith** [comment]
Ok. I had another idea. Do we even need to change the filter related code? I just tried the following tests on main and they seem to work. This seems to indicate that you could do something like:

```
"filter_op" : "ne",
"filter_arg": [""]
```

```diff
diff --git a/dig/dig_test.go b/dig/dig_test.go
index 01683bc..9eaecdd 100644
--- a/dig/dig_test.go
+++ b/dig/dig_test.go
@@ -440,6 +440,21 @@ func TestFilter(t *testing.T) {
                        "foo",
                        true,
                },
+               {
+                       Filter{Op: "eq", Arg: []string{""}},
+                       []byte{},
+                       true,
+               },
+               {
+                       Filter{Op: "ne", Arg: []string{""}},
+                       []byte{0x01},
+                       true,
+               },
+               {
+                       Filter{Op: "ne", Arg: []string{""}},
+                       []byte(nil),
+                       false,
+               },
                {
                        Filter{Op: "ne", Arg: []string{"bar"}},
                        "foo",
```

**Comment by ryandotsmith** [comment]
Another thought, it might be good to update the string decoding rules in the docs. I will do this asap. Something along the lines of:

> filter_arg is an array of strings. The string values will be decoded depending on the value of comparison. Namely, a string with a `0x` prefix will be decoded into `bytes`, a decimal string will be decoded into `uint` or `int`, a string of utf8 characters will be decoded into a `string`, and an empty string will be decoded as `null`.

**Comment by regynald** [comment]
Oh that would be perfect actually. I'll remove the filter changes

**Comment by ryandotsmith** [comment]
docs have been updated

**Pull request merged**
